# Full configuration reference: https://github.com/csarrazi/CsaGuzzleBundle/blob/2.x/src/Resources/doc/configuration_reference.md#configuration-reference
# Available client config options: http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
# and http://docs.guzzlephp.org/en/latest/request-options.html
csa_guzzle:
    profiler: '%kernel.debug%'
    clients:
        weather:
            config:
                base_uri: http://api.openweathermap.org
        flickr:
            config:
                class: App\Flickr\FlickrGuzzleClient
                base_uri: https://www.flickr.com
                headers:
                    Accept: application/json
    default_client: weather
#        my_client:
#            config:
#                base_uri: 'http://example.com'